# Generated by Django 5.2.7 on 2025-11-12 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Оценка')),
                ('notes', models.TextField(verbose_name='Заметки о посещении')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='user_photos/%Y/%m/%d/', verbose_name='Фотографии с посещения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to=settings.AUTH_USER_MODEL)),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.waypoint')),
            ],
            options={
                'verbose_name': 'Заметка о посещении',
                'verbose_name_plural': 'Заметки о посещениях',
            },
        ),
        migrations.CreateModel(
            name='FavoriteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, '⭐ Низкий'), (2, '⭐⭐ Средний'), (3, '⭐⭐⭐ Высокий'), (4, '⭐⭐⭐⭐ Очень высокий'), (5, '⭐⭐⭐⭐⭐ Обязательно посетить')], default=3, verbose_name='Приоритет')),
                ('planned_visit_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата посещения')),
                ('personal_notes', models.TextField(blank=True, verbose_name='Персональные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.waypoint', verbose_name='Точка маршрута')),
            ],
            options={
                'verbose_name': 'Избранная точка',
                'verbose_name_plural': 'Избранные точки',
                'unique_together': {('user', 'waypoint')},
            },
        ),
    ]
