# Generated by Django 5.2.7 on 2025-11-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('users', '0002_visitnote_favoritewaypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(choices=[('#1ABC9C', 'Бирюзовый'), ('#3498DB', 'Синий'), ('#9B59B6', 'Фиолетовый'), ('#E74C3C', 'Красный'), ('#F39C12', 'Оранжевый'), ('#2ECC71', 'Зеленый'), ('#34495E', 'Темно-синий')], default='#1ABC9C', max_length=20, verbose_name='Цвет маршрута')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный маршрут')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_routes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персональный маршрут',
                'verbose_name_plural': 'Персональные маршруты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в маршруте')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки для точки')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='users.personalroute')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.waypoint', verbose_name='Точка маршрута')),
            ],
            options={
                'verbose_name': 'Точка персонального маршрута',
                'verbose_name_plural': 'Точки персональных маршрутов',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
