# Generated by Django 5.2.7 on 2025-11-19 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personalroute_personalroutepoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitnote',
            name='photos',
        ),
        migrations.CreateModel(
            name='VisitNoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visit_notes/%Y/%m/%d/', verbose_name='Фотография')),
                ('caption', models.TextField(blank=True, verbose_name='Подпись к фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.visitnote')),
            ],
            options={
                'verbose_name': 'Фотография заметки',
                'verbose_name_plural': 'Фотографии заметок',
                'ordering': ['visit_note', 'order'],
            },
        ),
    ]
