# Generated by Django 5.2.7 on 2025-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_visitnote_photos_visitnoteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitnote',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/%Y/%m/%d/', verbose_name='Фотографии с посещения'),
        ),
    ]
