# Generated by Django 5.2.7 on 2025-11-20 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visitnote_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка действует до'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('basic', 'Базовый'), ('premium', 'Премиум')], default='free', max_length=20, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tourist', 'Турист'), ('traveler', 'Путешественник'), ('guide', 'Гид'), ('expert_guide', 'Гид-эксперт'), ('admin', 'Администратор')], default='tourist', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('specialties', models.TextField(blank=True, help_text='Через запятую', verbose_name='Специализации')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('verification_documents', models.FileField(blank=True, null=True, upload_to='guide_documents/%Y/%m/%d/', verbose_name='Документы для верификации')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
                ('completed_tours', models.IntegerField(default=0, verbose_name='Проведено туров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль гида',
                'verbose_name_plural': 'Профили гидов',
            },
        ),
    ]
