# Generated by Django 5.2.7 on 2025-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='static_map_image',
            field=models.ImageField(blank=True, help_text='Изображение карты маршрута для экспорта в PDF', null=True, upload_to='route_maps/%Y/%m/%d/', verbose_name='Статическое изображение карты маршрута'),
        ),
    ]
