# Generated by Django 5.2.7 on 2025-11-20 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_static_map_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='access_level',
            field=models.CharField(choices=[('public', 'Публичный'), ('premium', 'Только для премиум'), ('private', 'Приватный')], default='public', max_length=20, verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='route',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_routes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='route',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум маршрут'),
        ),
        migrations.AddField(
            model_name='route',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='route',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_routes', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='route',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Заметки модератора'),
        ),
        migrations.AddField(
            model_name='route',
            name='shares_count',
            field=models.IntegerField(default=0, verbose_name='Поделились'),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонен'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='route',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
